int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int recurse_root(int n, int prev);
int is_prime_number(int n);
int is_prime_helper(int n, int check);
int is_palindrome(char *s);
int palindrome_helper(char *s, int end, int beginning);
int wildcmp(char *s1, char *s2);
int cmp_helper(char *s1, char *s2, int s1length, int s2length);
char *gotolast(char *s, char c, int length);
